export declare function userDataDir(): string;
export declare function isPackaged(): boolean;
export declare function resourcesRoot(): string;
export declare function dbPath(): string;
export declare function assistantDbPath(): string;
export declare function uploadsDir(): string;
export declare function meiliDataDir(): string;
export declare function nextServerEntry(): string;
export declare function nodeBinary(): string;
export declare function nodeScript(rel: string): string;
export declare function nodeModulesPathForScripts(): string | null;
export declare function preloadPath(name: string): string;
export declare function portEnvKey(): string;
export declare const brandPaths: {
    userDataDir: typeof userDataDir;
    isPackaged: typeof isPackaged;
    resourcesRoot: typeof resourcesRoot;
    dbPath: typeof dbPath;
    assistantDbPath: typeof assistantDbPath;
    uploadsDir: typeof uploadsDir;
    meiliDataDir: typeof meiliDataDir;
    meiliBinary: () => string;
    nextServerEntry: typeof nextServerEntry;
    nodeBinary: typeof nodeBinary;
    nodeScript: typeof nodeScript;
    nodeModulesPathForScripts: typeof nodeModulesPathForScripts;
    preloadPath: typeof preloadPath;
    portEnvKey: typeof portEnvKey;
};
//# sourceMappingURL=paths.d.ts.map